
import { ProductCategory, StrainType, UserRole } from './types';
import type { Review, User } from './types';

export const reviews: Review[] = [
    {
        id: 1,
        name: 'Cosmic Gelato',
        brand: 'Galaxy Gardens',
        category: ProductCategory.FLOWER,
        strain: StrainType.HYBRID,
        image: 'https://picsum.photos/seed/cosmic/600/400',
        rating: 5,
        thc: 28.5,
        cbd: 0.5,
        effects: ['Euphoric', 'Creative', 'Relaxed'],
        flavors: ['Berry', 'Citrus', 'Sweet'],
        summary: 'A balanced hybrid that sends your mind soaring through the stars while keeping your body anchored in blissful relaxation.',
        fullReview: 'Cosmic Gelato from Galaxy Gardens is a truly stellar strain. The buds are dense, coated in a thick layer of trichomes that sparkle like a distant nebula. Its aroma is a complex bouquet of sweet berries and sharp citrus, with an earthy undertone. The high is immediate and uplifting, sparking creativity and conversation, making it perfect for social gatherings or artistic endeavors. As the initial euphoria a mellows, a gentle body buzz takes over, melting away stress without leading to couch-lock. A top-tier choice for any time of day.',
        likes: 138,
        price: 55.00,
        isFeatured: true,
        comments: [
            { id: 1, author: 'StarGazer', text: 'Absolutely out of this world! Best hybrid I\'ve had in ages.' },
            { id: 2, author: 'GrooveMaster', text: 'Perfect for a creative session. Two thumbs up!' },
        ],
    },
    {
        id: 2,
        name: 'Deep Sea OG',
        brand: 'Atlantic Cultivars',
        category: ProductCategory.FLOWER,
        strain: StrainType.INDICA,
        image: 'https://picsum.photos/seed/deepsea/600/400',
        rating: 4,
        thc: 24.2,
        cbd: 1.2,
        effects: ['Sleepy', 'Relaxed', 'Hungry'],
        flavors: ['Earthy', 'Pine', 'Pungent'],
        summary: 'Dive into deep relaxation with this potent indica, perfect for unwinding at the end of a long day.',
        fullReview: 'Deep Sea OG is a classic, heavy-hitting indica that lives up to its name. It pulls you down into a state of profound tranquility. The flavor is a robust mix of pine and damp earth, a taste that purists will appreciate. This is not a strain for productivity; its effects are deeply sedating, making it an excellent choice for managing pain, insomnia, or simply shutting off the mind before bed. Prepare for serious munchies and a long, restful sleep.',
        likes: 92,
        price: 48.50,
        isFeatured: true,
        comments: [
            { id: 1, author: 'CouchCaptain', text: 'This is my go-to for sleep. Knocks me out every time.' },
        ],
    },
    {
        id: 3,
        name: 'Super Lemon Haze',
        brand: 'Solar Flares',
        category: ProductCategory.FLOWER,
        strain: StrainType.SATIVA,
        image: 'https://picsum.photos/seed/lemonhaze/600/400',
        rating: 5,
        thc: 22.0,
        cbd: 0.3,
        effects: ['Energetic', 'Uplifted', 'Focused'],
        flavors: ['Lemon', 'Citrus', 'Zesty'],
        summary: 'A zesty and energetic sativa that provides a burst of focused energy and a positive outlook.',
        fullReview: 'Super Lemon Haze is a legendary sativa that never disappoints. The moment you open the bag, a powerful wave of fresh lemon zest hits your senses. The smoke is smooth and tastes exactly as it smells. The high is invigorating and cerebral, clearing away mental fog and inspiring a can-do attitude. It\'s an ideal daytime strain for tackling chores, creative projects, or enjoying the great outdoors. It provides a clean, long-lasting energy without the jitteriness some sativas can induce.',
        likes: 210,
        price: 52.00,
        isFeatured: true,
        comments: [
            { id: 1, author: 'DayTripper', text: 'My favorite sativa! The energy is clean and focused.' },
            { id: 2, author: 'ArtFan', text: 'Helps me get in the zone for painting.' },
            { id: 3, author: 'LemonLover', text: 'Tastes exactly like the name suggests!' },
        ],
    },
    {
        id: 4,
        name: 'Galactic Gummy Bites',
        brand: 'Edible Explorers',
        category: ProductCategory.EDIBLE,
        strain: StrainType.HYBRID,
        image: 'https://picsum.photos/seed/gummy/600/400',
        rating: 4,
        thc: 10, // per piece
        cbd: 0,
        effects: ['Giddy', 'Relaxed', 'Happy'],
        flavors: ['Mixed Berry', 'Sour', 'Sweet'],
        summary: 'Deliciously potent gummies that offer a consistent and enjoyable journey through the cosmos of consciousness.',
        fullReview: 'Galactic Gummy Bites are a fantastic option for those who prefer not to smoke. Each gummy is precisely dosed at 10mg THC, which allows for easy control over your experience. The mixed berry flavor is delightful, with a sour kick that masks any cannabis taste. The effects come on slowly, typically within 45-60 minutes, and build into a warm, full-body high that is both relaxing and mentally uplifting. Perfect for a movie night or a chill evening with friends.',
        likes: 77,
        price: 25.00,
        isFeatured: false,
        comments: [
            { id: 1, author: 'SweetTooth', text: 'Yummy and effective. What more could you ask for?' },
        ],
    },
    {
        id: 5,
        name: 'Nebula Nectar',
        brand: 'Concentrate Crafters',
        category: ProductCategory.CONCENTRATE,
        strain: StrainType.SATIVA,
        image: 'https://picsum.photos/seed/nectar/600/400',
        rating: 5,
        thc: 85.7,
        cbd: 0.8,
        effects: ['Creative', 'Focused', 'Euphoric'],
        flavors: ['Tropical', 'Mango', 'Sweet'],
        summary: 'An intensely flavorful and potent sativa concentrate that launches your mind into a creative stratosphere.',
        fullReview: 'Nebula Nectar is a premium live resin that boasts an incredible terpene profile. The aroma is a blast of tropical fruit, dominated by sweet mango and pineapple. The high THC content means a little goes a long way. The effects are fast-acting and intensely cerebral, sharpening focus and unlocking new streams of thought. It is an exceptional choice for experienced users looking for a powerful creative boost or a way to power through a complex task.',
        likes: 154,
        price: 65.00,
        isFeatured: true,
        comments: [
            { id: 1, author: 'DabMaster', text: 'So. Much. Flavor. The potency is off the charts too.' },
            { id: 2, author: 'CodeWizard', text: 'This is what I use when I need to focus and get work done.' },
        ],
    },
    {
        id: 6,
        name: 'Mariana Trench Vape',
        brand: 'Deep Vapes',
        category: ProductCategory.VAPE,
        strain: StrainType.INDICA,
        image: 'https://picsum.photos/seed/vape/600/400',
        rating: 4,
        thc: 91.2,
        cbd: 2.1,
        effects: ['Calm', 'Sleepy', 'Pain-Relief'],
        flavors: ['Grape', 'Earthy', 'Berry'],
        summary: 'A discreet and powerful vape cartridge designed for ultimate relaxation and deep, restorative sleep.',
        fullReview: 'The Mariana Trench Vape from Deep Vapes offers convenience without compromising on potency. This indica-dominant oil is smooth and flavorful, with notes of dark grape and a hint of earthy berry. The effects are profoundly calming, quickly quieting anxious thoughts and soothing physical discomfort. It\'s the perfect companion for a quiet night in, helping to ease the transition from a stressful day to a peaceful night\'s sleep. The hardware is reliable, providing a consistent draw every time.',
        likes: 89,
        price: 45.00,
        isFeatured: false,
        comments: [],
    },
];

export const users: User[] = [
    { id: 1, username: 'admin', password: 'admin', role: UserRole.ADMIN },
    { id: 2, username: 'user', password: 'password', role: UserRole.USER },
];
